name: Functional Selenium Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install selenium webdriver-manager pytest pytest-html

      - name: Run test and generate HTML report
        run: |
          source .venv/bin/activate
          pytest ci_smoke_test.py --html=report.html --self-contained-html --capture=tee-sys

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-html-report
          path: report.html

      - name: Upload screenshot if exists
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-artifacts
          path: screenshot_error.png
