name: Run Selenium Test on CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libxss1 \
            libgtk-3-0 \
            libgbm1 \
            libasound2

      - name: Install Python dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements.txt

      - name: Run Selenium test (CI)
        run: |
          venv/bin/python ci_smoke_test.py
